{
 "title": "R.E.D. metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "otel_scope_name",
    "query": {
     "query": "query_result(count by (otel_scope_name)(count_over_time(traces_span_metrics_calls_total[$__range])))"
    }
   },
   {
    "name": "service_name",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(traces_span_metrics_calls_total[$__range])))"
    }
   },
   {
    "name": "span_name",
    "query": {
     "query": "query_result(count by (span_name)(count_over_time(traces_span_metrics_calls_total{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operation Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Calls (Cumulative)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_span_metrics_calls_total{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\", span_name=~\"$span_name\"}[$__range]))",
     "legendFormat": "{{service_name}}: {{otel_scope_name}}"
    }
   ]
  },
  {
   "title": "Operations per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum by(span_name) (rate(traces_span_metrics_calls_total{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\", span_name=~\"$span_name\"}[5m]))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Percentage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(rate(traces_span_metrics_calls_total{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\", span_name=~\"$span_name\", status_code=\"STATUS_CODE_ERROR\"}[$__range])) * 100) / sum(rate(traces_span_metrics_calls_total{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\", span_name=~\"$span_name\"}[$__range]))",
       "legendFormat": "{{span_name}}"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 10 },
     "targets": [
      {
       "expr": "sum by(span_name) (rate(traces_span_metrics_calls_total{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\", span_name=~\"$span_name\", status_code=\"STATUS_CODE_ERROR\"}[5m])) != 0",
       "legendFormat": "{{span_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, span_name) (rate(traces_span_metrics_duration_milliseconds_bucket{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\", span_name=~\"$span_name\"}[5m])))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Latency p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le, span_name) (rate(traces_span_metrics_duration_milliseconds_bucket{otel_scope_name=\"$otel_scope_name\", service_name=\"$service_name\", span_name=~\"$span_name\"}[5m])))",
     "legendFormat": "{{span_name}}"
    }
   ]
  }
 ]
}