{
 "title": "Repositories R.E.D. metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Repositories RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le, span_name) (rate(traces_span_metrics_duration_milliseconds_count{service_name=\"Web\", otel_scope_name=\"DataLayer.Telemetry.EFCoreDiagnostics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories p75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le, span_name) (rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"Web\", otel_scope_name=\"DataLayer.Telemetry.EFCoreDiagnostics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, span_name) (rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"Web\", otel_scope_name=\"DataLayer.Telemetry.EFCoreDiagnostics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}